//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarReporting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReceipt
    {
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public double SellingPrice { get; set; }
        public double Qty { get; set; }
        public double TaxValue { get; set; }
        public double SoldPrice { get; set; }
        public int SaleId { get; set; }
    }
}
